package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"hycli-impex/internal"
	"hycli-impex/utils"

	"github.com/Salvadego/hac/hac"
	"github.com/spf13/cobra"
)

var (
	impexFile string
	impexOut  string
)

var importCmd = &cobra.Command{
	Use:   "import",
	Short: "Import Impex file",
	RunE: func(cmd *cobra.Command, args []string) error {
		if impexFile == "" {
			return fmt.Errorf("file is required")
		}

		data, err := os.ReadFile(impexFile)
		if err != nil {
			return err
		}

		c := internal.New(baseURL, username, password, skipVerify)
		ctx := context.Background()
		if err := internal.Login(c, ctx); err != nil {
			return err
		}

		resp, err := c.Impex.Import(ctx, hac.ImpexImportRequest{
			ScriptContent: string(data),
		})
		if err != nil {
			return err
		}

		printOutput(resp, internal.OutputFormat(impexOut))
		return nil
	},
}

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export Impex",
	RunE: func(cmd *cobra.Command, args []string) error {
		if impexFile == "" {
			return fmt.Errorf("file is required")
		}

		data, err := os.ReadFile(impexFile)
		if err != nil {
			return err
		}

		c := internal.New(baseURL, username, password, skipVerify)
		ctx := context.Background()
		if err := internal.Login(c, ctx); err != nil {
			return err
		}

		result, downloadURL, err := c.Impex.Export(ctx, hac.ImpexExportRequest{
			ScriptContent: string(data),
		})

		fmt.Printf("Export result: %s\n", result)

		if err != nil {
			return err
		}

		if downloadURL == "" {
			fmt.Println("No export zip generated by HAC")
			return nil
		}

		fmt.Println("Download URL:", downloadURL)

		zipBytes, err := c.Impex.DownloadExportZip(downloadURL)
		if err != nil {
			return err
		}

		out := impexOut
		if out == "" {
			out = "export.zip"
		}

		err = os.WriteFile(out, zipBytes, 0644)
		if err != nil {
			return err
		}

		fmt.Println("Export ZIP saved as", out)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(importCmd, exportCmd)

	importCmd.Flags().StringVarP(&impexFile, "file", "f", "", "File containing Impex data")
	importCmd.Flags().StringVarP(&impexOut, "output", "o", "table", "table|json")
	importCmd.RegisterFlagCompletionFunc("output", utils.CompleteOutputFormat)

	exportCmd.Flags().StringVarP(&impexFile, "file", "f", "", "File containing Impex export script")
	exportCmd.Flags().StringVarP(&impexOut, "output", "o", "export.zip", "Export ZIP file")
}

func printOutput(resp any, format internal.OutputFormat) {
	switch format {
	case internal.OutputTable:
		fmt.Printf("%+v\n", resp)
	case internal.OutputJSON:
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(string(b))
	}
}
